/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  BookTrip,  CalculateSavingsGoal,  CoordinatorDone,  CoordinatorRespond,  CreateShoppingList,  Done,  FinanceDone,  FinanceRespond,  GetBudgetSummary,  GetInvestmentInfo,  GetNutrition,  GetWeather,  InvokeFinanceAgent,  InvokeRecipeAgent,  InvokeTravelAgent,  PlanMeal,  RecipeDone,  RecipeRespond,  RespondToUser,  SearchFlights,  SearchHotels,  SearchRecipes,  TrackExpense } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BookTrip {
      intent?: "book_trip" | null
      destination?: string | null
      startDate?: string | null
      endDate?: string | null
    }
    export interface CalculateSavingsGoal {
      intent?: "calculate_savings_goal" | null
      targetAmount?: number | null
      currentSavings?: number | null
      monthlyContribution?: number | null
    }
    export interface CoordinatorDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface CoordinatorRespond {
      intent?: "respond" | null
      message?: string | null
    }
    export interface CreateShoppingList {
      intent?: "create_shopping_list" | null
      recipes: string[]
    }
    export interface Done {
      intent?: "done" | null
      message?: string | null
    }
    export interface FinanceDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface FinanceRespond {
      intent?: "respond" | null
      message?: string | null
    }
    export interface GetBudgetSummary {
      intent?: "get_budget_summary" | null
      period?: string | null
    }
    export interface GetInvestmentInfo {
      intent?: "get_investment_info" | null
      symbol?: string | null
    }
    export interface GetNutrition {
      intent?: "get_nutrition" | null
      ingredient?: string | null
    }
    export interface GetWeather {
      intent?: "get_weather" | null
      city?: string | null
    }
    export interface InvokeFinanceAgent {
      intent?: "invoke_finance_agent" | null
      query?: string | null
    }
    export interface InvokeRecipeAgent {
      intent?: "invoke_recipe_agent" | null
      query?: string | null
    }
    export interface InvokeTravelAgent {
      intent?: "invoke_travel_agent" | null
      query?: string | null
    }
    export interface PlanMeal {
      intent?: "plan_meal" | null
      mealType?: string | null
      preferences: string[]
    }
    export interface RecipeDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface RecipeRespond {
      intent?: "respond" | null
      message?: string | null
    }
    export interface RespondToUser {
      intent?: "respond" | null
      message?: string | null
    }
    export interface SearchFlights {
      intent?: "search_flights" | null
      from?: string | null
      to?: string | null
      date?: string | null
    }
    export interface SearchHotels {
      intent?: "search_hotels" | null
      city?: string | null
      checkIn?: string | null
      checkOut?: string | null
    }
    export interface SearchRecipes {
      intent?: "search_recipes" | null
      ingredients: string[]
      dietary?: string | null
    }
    export interface TrackExpense {
      intent?: "track_expense" | null
      category?: string | null
      amount?: number | null
      description?: string | null
    }
export type CoordinatorTools = InvokeTravelAgent | InvokeRecipeAgent | InvokeFinanceAgent | CoordinatorRespond | CoordinatorDone | null

export type FinanceTools = TrackExpense | GetBudgetSummary | GetInvestmentInfo | CalculateSavingsGoal | FinanceRespond | FinanceDone | null

export type RecipeTools = SearchRecipes | GetNutrition | PlanMeal | CreateShoppingList | RecipeRespond | RecipeDone | null

export type TravelTools = GetWeather | SearchFlights | SearchHotels | BookTrip | RespondToUser | Done | null

}